language: java
gradle check
gradle assemble
jdk:
 - oraclejdk8
 - oraclejdk7
 - openjdk7
script:
  - jdk_switcher use oraclejdk8
  - # do stuff with Java 8
  - jdk_switcher use oraclejdk7
  - # do stuff with Java 7
